<div id="getsimple_information" data-bind="scope:'getsimple_information'">
    <!-- ko template: getTemplate() --><!-- /ko -->
    <script type="text/x-magento-init">
    {
        "#getsimple_information": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "getsimple_information": {
                        "component": "Simpl_Splitpay/js/view/popup"
                    }
                }
            }
        }
    }
    </script>  
</div>